openapi: 3.0.3
info:
  title: Book Management API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
paths:
  /auth/token:
    post:
      summary: Lấy JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Trả về token
  /api/books:
    get:
      summary: Lấy danh sách sách
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Thành công
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
