openapi: 3.0.3
info:
  title: Book Management API
  description: >
    API demo cho **Buổi 4 - API Specification & OpenAPI**
    Bao gồm xác thực JWT (stateless) và Swagger UI.
  version: 1.0.0

servers:
  - url: http://127.0.0.1:5000

paths:
  /auth/token:
    post:
      summary: Lấy JWT token
      description: Đăng nhập bằng username/password để nhận access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Trả về token hợp lệ
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
        "401":
          description: Sai tài khoản hoặc mật khẩu

  /api/books:
    get:
      summary: Lấy danh sách sách
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Danh sách các sách
    post:
      summary: Thêm sách mới
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book"
      responses:
        "201":
          description: Sách đã được thêm

  /api/books/{book_id}:
    get:
      summary: Lấy thông tin sách theo ID
      security:
        - bearerAuth: []
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Sách được tìm thấy
    put:
      summary: Cập nhật sách
      security:
        - bearerAuth: []
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book"
      responses:
        "200":
          description: Sách đã được cập nhật
    delete:
      summary: Xóa sách
      security:
        - bearerAuth: []
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Xóa thành công

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Book:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
